spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: cloud_user
    password: cloud_password

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  session:
    timeout: 30m
    data:
      redis:
        namespace: cloud-storage:session
        flush-mode: on-save
        save-mode: on-set-attribute

storage:
  s3:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin123
    bucket: user-files

logging:
  level:
    root: info
