spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username:
    password:

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  session:
    store-type: redis
    session:
      timeout: 30m
      data:
        redis:
          namespace: cloud-storage:session
        flush-mode: on-save
        save-mode: on-set-attribute

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      location: /tmp
      file-size-threshold: 2MB

server:
  tomcat:
    max-swallow-size: -1

storage:
  s3:
    endpoint: http://localhost:9000
    accessKey:
    secretKey:
    bucket: user-files

springdoc:
  override-with-generic-response: false
