spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: cloud_user
    password: cloud_password

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  session:
    store-type: redis
    session:
      timeout: 30m
      data:
        redis:
          namespace: cloud-storage:session
        flush-mode: on-save
        save-mode: on-set-attribute

  data:
    redis:
      host: localhost
      port: 6379


storage:
  s3:
    endpoint: http://localhost:9000
    accessKey: minioadmin
    secretKey: minioadmin123
    bucket: user-files

logging:
  level:
    root: info
