spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${POSTGRES_DB:cloud_storage}
    username: ${POSTGRES_USER:cloud_user}
    password: ${POSTGRES_PASSWORD:cloud_password}

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: ${REDIS_NAMESPACE:cloud-storage:session}
      flush-mode: on-save
      save-mode: on-set-attribute

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
      location: /tmp
      file-size-threshold: 2MB

server:
  tomcat:
    max-swallow-size: -1

storage:
  s3:
    endpoint: ${STORAGE_S3_ENDPOINT:http://localhost:9000}
    accessKey: ${STORAGE_S3_ACCESSKEY:minioadmin}
    secretKey: ${STORAGE_S3_SECRETKEY:minioadmin123}
    bucket: ${STORAGE_S3_BUCKET:user-files}

springdoc:
  override-with-generic-response: false
